GET http://localhost:5294

###

GET http://localhost:5294/?secure=true&authenticated=true

###

GET http://localhost:5294/unauthorized?secure=true

###

GET http://localhost:5294/?secure=true&authenticated=true&input=<script>

###

GET http://localhost:5294/?secure=true

###