GET http://localhost:5296/blogs

###

POST http://localhost:5296/newBlog/2nd-Blog?body=If_this_works_its_a_miracle!
content-type: application/json

###

POST http://localhost:5296/reset
# pass: P@ssword!

###

POST http://localhost:5296/newBlog
content-type: application/json

{
    "Title": "Json Blog",
    "Body": "No way i remembered this :haha:"
}

###
